### PR TITLE
Fix warnings caused by zero sized structures.

### PR DESCRIPTION
**Pull request by csherratt**

### CODE REVIEW

**Comment by csherratt** [comment]
Should allow https://github.com/bjz/gl-rs/pull/357 to build

**Comment by tomaka** [comment]
Well, the proper fix would be to remove the warning.

There are only three types as far as I can see: GLsync, XVisualInfo and Display.

**Comment by bjz** [comment]
What does the `improper_ctypes` thing actually do?

**Comment by csherratt** [comment]
As far as I understand the `improper_ctypes` is rejecting the empty structs, which are illegal in C but legal in Rust. I'm not sure how else to express an opaque pointer in rust.

**Comment by csherratt** [comment]
Ok, this should have fixed the root cause now. @bjz @tomaka r+?

**Comment by tomaka** [comment]
I find it weird that it works, but why not.

**Comment by csherratt** [comment]
@tomaka I was following the style that `bindgen` uses. I agree, I can't see how this is better.

**Pull request merged**
