### PR TITLE
Upgrade to libc 0.2

### PR DESCRIPTION
**Pull request by mbrubeck**

### CODE REVIEW

**Comment by bjz** [comment]
Hmm, fails test - don't know if that is related to this change though.

**Comment by csherratt** [comment]
It's not related to these changes. I can produce it locally without them.

**Comment by bjz** [comment]
Okiedokie, merging. Should this be a revision, or a minor version bump do you think?

**Comment by tomaka** [comment]
We should just entirely remove anything related to libc from the API. Turn `*const libc::foo` into `()` and make the conversion in the wrapper functions if necessary.

And also destroy `gl_common` while we're at it.

**Pull request merged**
