### PR TITLE
Use std::os::raw::* instead of libc::*, and remove the dependency

### PR DESCRIPTION
**Pull request by tomaka**
- Replaces `libc::c_foo` with `std::os::raw::c_foo`.
- Replaces `intptr_t` and `ptrdiff_t` with `isize` because these types are not in `std::os::raw`.
- Replaces `c_void` with `()` because they say that `c_void` shouldn't be used for FFI: https://doc.rust-lang.org/stable/std/os/raw/enum.c_void.html.

### CODE REVIEW

**Comment by tomaka** [comment]
Ah nevermind, `*const ()` should really be `*const c_void`.

**Comment by tomaka** [comment]
Note that we should probably switch from `std::os::raw` to `core::os::raw` once it's stable, so that people can use gl-rs without a stdlib.

**Comment by bjz** [comment]
cc bjz/glfw-rs#328 #364 #366

**Comment by bjz** [comment]
Clarified the PR title. Will merge. I'm not in the position to update to 0.4.0 right now - you are welcome to do it @tomaka.

**Pull request merged**
