### PR TITLE
Fix GLFW initialization in examples

### PR DESCRIPTION
**Pull request by penberg**
Fix unwrap and use 'mut' where appropriate.

Signed-off-by: Pekka Enberg <penberg@iki.fi>

### CODE REVIEW

**Comment by tomaka** [comment]
`unwrap()` not working is a problem coming from GLFW. `unwrap` is the correct thing to do here.

**Comment by penberg** [comment]
@tomaka Okay, I am a Rust newbie so I don't really claim to understand what's going on here. GLFW examples were switched from ``unwrap`` in commit https://github.com/bjz/glfw-rs/commit/bc1b352c814af44a0f9d6cf8c365b35db5b0948a which is why I assumed that would be the appropriate thing to do here as well.

**Comment by tomaka** [comment]
I left a word about it in https://github.com/bjz/glfw-rs/pull/280

**Comment by penberg** [comment]
This is getting fixed in glfw-rs so I'm closing the pull request.

**Comment by bjz** [comment]
Sorry for the bother!

**Pull request closed without merging**
