### PR TITLE
Update the gl/examples to build on latest rust and glfw

### PR DESCRIPTION
**Pull request by navaati**
I have not, however, been able to update the struct_triangle.rs example

### CODE REVIEW

**Comment by bvssvni** [comment]
Looks good.

**Comment by bvssvni** [comment]
I'm having problems building examples from the "gl" folder.

```
$ cargo build --example static_triangle
no example target named `static_triangle`
```

**Comment by tomaka** [comment]
You need to remove [this line](https://github.com/bjz/gl-rs/blob/b856b6141853adf23bd8fbae13a9de161ab1162e/gl/Cargo.toml#L1).

**Comment by bvssvni** [comment]
Both "static_basic" and "static_triangle" need to add ` as *const ()` to work.

**Comment by bvssvni** [comment]
The reason that "struct_triangle" does not work is, if I remember correctly, that `generate_gl_bindings!` was replaced by a build script.

**Pull request closed without merging**
